<a href="https://colab.research.google.com/github/raviakasapu/DeepLearningPyTorch/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

https://www.learnpytorch.io/00_pytorch_fundamentals/

### import libraries

In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


### Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([1,7])
vector

tensor([1, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
# matrix
matrix = torch.tensor([[1,2],
                      [3,2]])
matrix

tensor([[1, 2],
        [3, 2]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor 

tensor = torch.tensor([[[1,2,3],[2,3,4],[3,4,5]]])

In [14]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors

In [19]:
#create a random tensor
#of shape (3,4)

random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.7498, 0.9983, 0.7029, 0.4444],
         [0.8130, 0.6599, 0.8919, 0.4814],
         [0.3264, 0.0859, 0.8112, 0.1334]],

        [[0.7264, 0.1967, 0.4988, 0.4203],
         [0.3329, 0.5832, 0.5962, 0.0666],
         [0.5908, 0.9196, 0.3744, 0.5368]]])

In [22]:
# tensor with shape same as image tensor
random_image_tensor = torch.rand(size=(3,224,224)) # color channels, height, width
random_image_tensor.ndim

3

In [23]:
# tensor with 0's and 1's
zero = torch.zeros(size=(1,3,4))
zero

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### arange

In [25]:
tn_arange = torch.arange(start=1,end=12,step=2)
tn_arange

tensor([ 1,  3,  5,  7,  9, 11])

In [26]:
ten_zeros = torch.zeros_like(input=tn_arange)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

### Data Types

In [29]:
#float 32

f32_tnsr = torch.tensor([3.0,6.0,9.0],dtype=None)
f32_tnsr.dtype

torch.float32

In [30]:
f16_tnsr = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
f16_tnsr.dtype

torch.float16

In [31]:
f16_tnsr_2 = f32_tnsr.type(torch.float16)
f16_tnsr_2.dtype

torch.float16