<a href="https://colab.research.google.com/github/raviakasapu/DeepLearningPyTorch/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

https://www.learnpytorch.io/00_pytorch_fundamentals/

### import libraries

In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


### Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([1,7])
vector

tensor([1, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
matrix = torch.tensor([[1,2],
                      [3,2]])
matrix

tensor([[1, 2],
        [3, 2]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# Tensor 

tensor = torch.tensor([[[1,2,3],[2,3,4],[3,4,5]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors

In [15]:
#create a random tensor
#of shape (3,4)

random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.6464, 0.0367, 0.2175, 0.3700],
         [0.4777, 0.4236, 0.2581, 0.4367],
         [0.3959, 0.2307, 0.2338, 0.6359]],

        [[0.5380, 0.7390, 0.4659, 0.7473],
         [0.4137, 0.6104, 0.9368, 0.8039],
         [0.3022, 0.6203, 0.2643, 0.2682]]])

In [16]:
# tensor with shape same as image tensor
random_image_tensor = torch.rand(size=(3,224,224)) # color channels, height, width
random_image_tensor.ndim

3

In [17]:
# tensor with 0's and 1's
zero = torch.zeros(size=(1,3,4))
zero

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### arange

In [18]:
tn_arange = torch.arange(start=1,end=12,step=2)
tn_arange

tensor([ 1,  3,  5,  7,  9, 11])

In [19]:
ten_zeros = torch.zeros_like(input=tn_arange)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

### Data Types

In [20]:
#float 32

f32_tnsr = torch.tensor([3.0,6.0,9.0],dtype=None)
f32_tnsr.dtype

torch.float32

In [21]:
f16_tnsr = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
f16_tnsr.dtype

torch.float16

In [22]:
f16_tnsr_2 = f32_tnsr.type(torch.float16)
f16_tnsr_2.dtype

torch.float16

In [23]:
tnsr_16_32 = f32_tnsr * f16_tnsr_2
tnsr_16_32.dtype

torch.float32

In [24]:
print(tnsr_16_32)
print(tnsr_16_32.dtype)
print(tnsr_16_32.ndim)
print(tnsr_16_32.shape)
print(tnsr_16_32.device)

tensor([ 9., 36., 81.])
torch.float32
1
torch.Size([3])
cpu


### Tensor operations - Manipulating

- Addition
- Subtraction
- Multiplication 
 - Element wise
 - Matrix
- Division

In [25]:
random_tensor_1 = torch.rand(2,3,4)
random_tensor_2 = torch.rand(2,3,4)

In [26]:
random_tensor_1

tensor([[[0.8581, 0.6321, 0.3025, 0.3525],
         [0.7769, 0.2982, 0.0968, 0.5115],
         [0.8035, 0.6549, 0.1064, 0.1746]],

        [[0.6960, 0.5502, 0.0995, 0.0443],
         [0.5861, 0.0540, 0.8640, 0.1173],
         [0.5561, 0.8640, 0.9137, 0.3319]]])

In [27]:
random_tensor_1 + 10
# or torch.add(random_tensor_1,10)

tensor([[[10.8581, 10.6321, 10.3025, 10.3525],
         [10.7769, 10.2982, 10.0968, 10.5115],
         [10.8035, 10.6549, 10.1064, 10.1746]],

        [[10.6960, 10.5502, 10.0995, 10.0443],
         [10.5861, 10.0540, 10.8640, 10.1173],
         [10.5561, 10.8640, 10.9137, 10.3319]]])

In [28]:
torch.subtract(random_tensor_1,10)

tensor([[[-9.1419, -9.3679, -9.6975, -9.6475],
         [-9.2231, -9.7018, -9.9032, -9.4885],
         [-9.1965, -9.3451, -9.8936, -9.8254]],

        [[-9.3040, -9.4498, -9.9005, -9.9557],
         [-9.4139, -9.9460, -9.1360, -9.8827],
         [-9.4439, -9.1360, -9.0863, -9.6681]]])

In [29]:
torch.mul(random_tensor_1,3)

tensor([[[2.5743, 1.8963, 0.9076, 1.0575],
         [2.3308, 0.8946, 0.2903, 1.5345],
         [2.4105, 1.9646, 0.3192, 0.5238]],

        [[2.0881, 1.6507, 0.2985, 0.1328],
         [1.7583, 0.1619, 2.5919, 0.3518],
         [1.6682, 2.5920, 2.7412, 0.9957]]])

In [30]:
random_tensor_1/5

tensor([[[0.1716, 0.1264, 0.0605, 0.0705],
         [0.1554, 0.0596, 0.0194, 0.1023],
         [0.1607, 0.1310, 0.0213, 0.0349]],

        [[0.1392, 0.1100, 0.0199, 0.0089],
         [0.1172, 0.0108, 0.1728, 0.0235],
         [0.1112, 0.1728, 0.1827, 0.0664]]])

In [31]:
random_tensor_1 = torch.rand(2,3,4)
random_tensor_2 = torch.rand(2,3,4)

In [32]:
%%time
tnsr_matrix_element=torch.mul(random_tensor_1,random_tensor_2)
print(tnsr_matrix_element)
print(tnsr_matrix_element.ndim)
print(f"shape of random_tensor_1",random_tensor_1.shape)
print(f"shape of random_tensor_2",random_tensor_2.shape)
print(f"shape of tnsr_matrix_mult",tnsr_matrix_element.shape)


tensor([[[0.3332, 0.0278, 0.0296, 0.0023],
         [0.6192, 0.7280, 0.8070, 0.0873],
         [0.1714, 0.7726, 0.0032, 0.2169]],

        [[0.1283, 0.0116, 0.5341, 0.1226],
         [0.0240, 0.1108, 0.2603, 0.2371],
         [0.0423, 0.6416, 0.0165, 0.5007]]])
3
shape of random_tensor_1 torch.Size([2, 3, 4])
shape of random_tensor_2 torch.Size([2, 3, 4])
shape of tnsr_matrix_mult torch.Size([2, 3, 4])
CPU times: user 3.73 ms, sys: 0 ns, total: 3.73 ms
Wall time: 6.61 ms


In [33]:
random_tensor_1 = torch.rand(2,3,4)
random_tensor_2 = torch.rand(2,4,4)

In [34]:
%%time
tnsr_matrix_mult = torch.matmul(random_tensor_1, random_tensor_2)
print(tnsr_matrix_mult)
print(tnsr_matrix_mult.ndim)
print(f"shape of random_tensor_1",random_tensor_1.shape)
print(f"shape of random_tensor_2",random_tensor_2.shape)
print(f"shape of tnsr_matrix_mult",tnsr_matrix_mult.shape)


tensor([[[0.9677, 0.9599, 0.4968, 1.3072],
         [1.3288, 1.6020, 0.6242, 1.6688],
         [0.9339, 1.3696, 0.4914, 1.1742]],

        [[0.9927, 0.9583, 0.6237, 0.5777],
         [1.1945, 0.9995, 0.7604, 0.7605],
         [0.5937, 0.3389, 0.2890, 0.4131]]])
3
shape of random_tensor_1 torch.Size([2, 3, 4])
shape of random_tensor_2 torch.Size([2, 4, 4])
shape of tnsr_matrix_mult torch.Size([2, 3, 4])
CPU times: user 3.33 ms, sys: 49 µs, total: 3.38 ms
Wall time: 6.62 ms


# Tensor aggregation
# min, max, mean, sum

In [35]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [38]:
x.dtype

torch.int64

In [37]:
torch.mean(x)

RuntimeError: ignored

In [39]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [41]:
x.sum(),torch.sum(x)

(tensor(450), tensor(450))