<a href="https://colab.research.google.com/github/raviakasapu/DeepLearningPyTorch/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

https://www.learnpytorch.io/00_pytorch_fundamentals/

### import libraries

In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


### Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([1,7])
vector

tensor([1, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
matrix = torch.tensor([[1,2],
                      [3,2]])
matrix

tensor([[1, 2],
        [3, 2]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# Tensor 

tensor = torch.tensor([[[1,2,3],[2,3,4],[3,4,5]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors

In [15]:
#create a random tensor
#of shape (3,4)

random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.2273, 0.0088, 0.8227, 0.6476],
         [0.3009, 0.2500, 0.2704, 0.2963],
         [0.1952, 0.2215, 0.7357, 0.9915]],

        [[0.8361, 0.0406, 0.8359, 0.3473],
         [0.9245, 0.8672, 0.8324, 0.8146],
         [0.3175, 0.6225, 0.0502, 0.9908]]])

In [16]:
# tensor with shape same as image tensor
random_image_tensor = torch.rand(size=(3,224,224)) # color channels, height, width
random_image_tensor.ndim

3

In [17]:
# tensor with 0's and 1's
zero = torch.zeros(size=(1,3,4))
zero

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### arange

In [18]:
tn_arange = torch.arange(start=1,end=12,step=2)
tn_arange

tensor([ 1,  3,  5,  7,  9, 11])

In [19]:
ten_zeros = torch.zeros_like(input=tn_arange)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

### Data Types

In [20]:
#float 32

f32_tnsr = torch.tensor([3.0,6.0,9.0],dtype=None)
f32_tnsr.dtype

torch.float32

In [21]:
f16_tnsr = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
f16_tnsr.dtype

torch.float16

In [22]:
f16_tnsr_2 = f32_tnsr.type(torch.float16)
f16_tnsr_2.dtype

torch.float16

In [23]:
tnsr_16_32 = f32_tnsr * f16_tnsr_2
tnsr_16_32.dtype

torch.float32

In [24]:
print(tnsr_16_32)
print(tnsr_16_32.dtype)
print(tnsr_16_32.ndim)
print(tnsr_16_32.shape)
print(tnsr_16_32.device)

tensor([ 9., 36., 81.])
torch.float32
1
torch.Size([3])
cpu


### Tensor operations - Manipulating

- Addition
- Subtraction
- Multiplication 
 - Element wise
 - Matrix
- Division

In [25]:
random_tensor_1 = torch.rand(2,3,4)
random_tensor_2 = torch.rand(2,3,4)

In [26]:
random_tensor_1

tensor([[[0.5034, 0.7819, 0.8692, 0.7775],
         [0.4289, 0.0403, 0.4799, 0.4308],
         [0.5506, 0.9214, 0.7420, 0.2233]],

        [[0.5967, 0.9467, 0.7245, 0.2933],
         [0.1046, 0.9137, 0.4703, 0.9375],
         [0.2302, 0.1999, 0.0426, 0.9387]]])

In [27]:
random_tensor_1 + 10
# or torch.add(random_tensor_1,10)

tensor([[[10.5034, 10.7819, 10.8692, 10.7775],
         [10.4289, 10.0403, 10.4799, 10.4308],
         [10.5506, 10.9214, 10.7420, 10.2233]],

        [[10.5967, 10.9467, 10.7245, 10.2933],
         [10.1046, 10.9137, 10.4703, 10.9375],
         [10.2302, 10.1999, 10.0426, 10.9387]]])

In [28]:
torch.subtract(random_tensor_1,10)

tensor([[[-9.4966, -9.2181, -9.1308, -9.2225],
         [-9.5711, -9.9597, -9.5201, -9.5692],
         [-9.4494, -9.0786, -9.2580, -9.7767]],

        [[-9.4033, -9.0533, -9.2755, -9.7067],
         [-9.8954, -9.0863, -9.5297, -9.0625],
         [-9.7698, -9.8001, -9.9574, -9.0613]]])

In [29]:
torch.mul(random_tensor_1,3)

tensor([[[1.5102, 2.3456, 2.6076, 2.3326],
         [1.2868, 0.1210, 1.4396, 1.2924],
         [1.6518, 2.7641, 2.2259, 0.6699]],

        [[1.7902, 2.8402, 2.1735, 0.8798],
         [0.3137, 2.7410, 1.4110, 2.8124],
         [0.6906, 0.5997, 0.1279, 2.8162]]])

In [30]:
random_tensor_1/5

tensor([[[0.1007, 0.1564, 0.1738, 0.1555],
         [0.0858, 0.0081, 0.0960, 0.0862],
         [0.1101, 0.1843, 0.1484, 0.0447]],

        [[0.1193, 0.1893, 0.1449, 0.0587],
         [0.0209, 0.1827, 0.0941, 0.1875],
         [0.0460, 0.0400, 0.0085, 0.1877]]])

In [31]:
random_tensor_1 = torch.rand(2,3,4)
random_tensor_2 = torch.rand(2,3,4)

In [32]:
%%time
tnsr_matrix_element=torch.mul(random_tensor_1,random_tensor_2)
print(tnsr_matrix_element)
print(tnsr_matrix_element.ndim)
print(f"shape of random_tensor_1",random_tensor_1.shape)
print(f"shape of random_tensor_2",random_tensor_2.shape)
print(f"shape of tnsr_matrix_mult",tnsr_matrix_element.shape)


tensor([[[0.3092, 0.5423, 0.0498, 0.0478],
         [0.0310, 0.9290, 0.2365, 0.1808],
         [0.3870, 0.4379, 0.4958, 0.5688]],

        [[0.5176, 0.1800, 0.0078, 0.4505],
         [0.1341, 0.0089, 0.1050, 0.0515],
         [0.4540, 0.0309, 0.2210, 0.7441]]])
3
shape of random_tensor_1 torch.Size([2, 3, 4])
shape of random_tensor_2 torch.Size([2, 3, 4])
shape of tnsr_matrix_mult torch.Size([2, 3, 4])
CPU times: user 2.45 ms, sys: 77 µs, total: 2.53 ms
Wall time: 4 ms


In [33]:
random_tensor_1 = torch.rand(2,3,4)
random_tensor_2 = torch.rand(2,4,4)

In [34]:
%%time
tnsr_matrix_mult = torch.matmul(random_tensor_1, random_tensor_2)
print(tnsr_matrix_mult)
print(tnsr_matrix_mult.ndim)
print(f"shape of random_tensor_1",random_tensor_1.shape)
print(f"shape of random_tensor_2",random_tensor_2.shape)
print(f"shape of tnsr_matrix_mult",tnsr_matrix_mult.shape)


tensor([[[1.1672, 1.3757, 1.6217, 1.7995],
         [1.5089, 1.3603, 1.9364, 2.0081],
         [0.5187, 0.8908, 0.6889, 1.0093]],

        [[1.3732, 1.3851, 1.1785, 1.4536],
         [1.1672, 1.0949, 1.0086, 1.0465],
         [0.7961, 1.0358, 1.0644, 1.2232]]])
3
shape of random_tensor_1 torch.Size([2, 3, 4])
shape of random_tensor_2 torch.Size([2, 4, 4])
shape of tnsr_matrix_mult torch.Size([2, 3, 4])
CPU times: user 2.79 ms, sys: 0 ns, total: 2.79 ms
Wall time: 6.21 ms


# Tensor aggregation
# min, max, mean, sum

In [35]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [37]:
x.dtype

torch.int64

In [38]:
torch.mean(x)

RuntimeError: ignored

In [39]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [40]:
x.sum(),torch.sum(x)

(tensor(450), tensor(450))

# positonal min and mx
# argmin and argmax

In [41]:
x+2

tensor([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [42]:
x.argmin()

tensor(0)

In [43]:
x.argmax()

tensor(9)

In [44]:
x[x.argmax()]

tensor(90)

In [45]:
x.max()

tensor(90)

# Reshape, stacking, squeezing, unsqueeze

In [46]:
x = torch.arange(0,6,1)
x.shape

torch.Size([6])

In [47]:
x.reshape(1,3,2)

tensor([[[0, 1],
         [2, 3],
         [4, 5]]])

In [48]:
x_1 = x.reshape(2,1,3)
x_1.shape,x_1

(torch.Size([2, 1, 3]),
 tensor([[[0, 1, 2]],
 
         [[3, 4, 5]]]))

In [49]:
x_stacked = torch.stack([x_1,x_1],dim=0)
x_stacked.shape,x_stacked

(torch.Size([2, 2, 1, 3]),
 tensor([[[[0, 1, 2]],
 
          [[3, 4, 5]]],
 
 
         [[[0, 1, 2]],
 
          [[3, 4, 5]]]]))

In [50]:
x_stacked = torch.stack([x_1,x_1],dim=1)
x_stacked.shape,x_stacked

(torch.Size([2, 2, 1, 3]),
 tensor([[[[0, 1, 2]],
 
          [[0, 1, 2]]],
 
 
         [[[3, 4, 5]],
 
          [[3, 4, 5]]]]))

In [51]:
y=x_stacked.squeeze()
y.shape,y

(torch.Size([2, 2, 3]),
 tensor([[[0, 1, 2],
          [0, 1, 2]],
 
         [[3, 4, 5],
          [3, 4, 5]]]))

In [52]:
z = y.unsqueeze(dim=0)
z.shape, z

(torch.Size([1, 2, 2, 3]),
 tensor([[[[0, 1, 2],
           [0, 1, 2]],
 
          [[3, 4, 5],
           [3, 4, 5]]]]))

In [53]:
x_permute = x_1.permute(0,2,1)
x_1.shape, x_permute.shape

(torch.Size([2, 1, 3]), torch.Size([2, 3, 1]))

In [54]:
x_1

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [55]:
x_1[1,0,2]=100
x_1

tensor([[[  0,   1,   2]],

        [[  3,   4, 100]]])

In [56]:
x_permute.shape, x_permute

(torch.Size([2, 3, 1]),
 tensor([[[  0],
          [  1],
          [  2]],
 
         [[  3],
          [  4],
          [100]]]))

In [57]:
x_permute[1][2][0]

tensor(100)

In [58]:
x_permute[:,2,0]

tensor([  2, 100])

# PyTorch and Numpy

In [59]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

array

array([1., 2., 3., 4., 5., 6., 7.])

In [60]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [61]:
array[2]=100
array, tensor

(array([  1.,   2., 100.,   4.,   5.,   6.,   7.]),
 tensor([  1.,   2., 100.,   4.,   5.,   6.,   7.], dtype=torch.float64))

In [62]:
array = array + 1
array, tensor

(array([  2.,   3., 101.,   5.,   6.,   7.,   8.]),
 tensor([  1.,   2., 100.,   4.,   5.,   6.,   7.], dtype=torch.float64))

In [63]:
array[4]=400
array, tensor

(array([  2.,   3., 101.,   5., 400.,   7.,   8.]),
 tensor([  1.,   2., 100.,   4.,   5.,   6.,   7.], dtype=torch.float64))

In [64]:
array = array + 4
array, tensor

(array([  6.,   7., 105.,   9., 404.,  11.,  12.]),
 tensor([  1.,   2., 100.,   4.,   5.,   6.,   7.], dtype=torch.float64))

In [65]:
tensor_1 = torch.ones(7)
numpy_tensor = tensor_1.numpy()

tensor_1, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [66]:
tensor_1.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [67]:
tensor_1 = tensor_1 + 2
tensor_1, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility
### take random out of random

**random seed**

In [68]:
t_a = torch.rand(3,4)
t_b = torch.rand(3,4)

t_a, t_b

(tensor([[0.7850, 0.3302, 0.8529, 0.1173],
         [0.0765, 0.4041, 0.6127, 0.0488],
         [0.4819, 0.0152, 0.5791, 0.9571]]),
 tensor([[0.3773, 0.5459, 0.9800, 0.3306],
         [0.1563, 0.5772, 0.8702, 0.2808],
         [0.2861, 0.7563, 0.7424, 0.5730]]))

In [69]:
t_a == t_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [70]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
t_aa = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
t_bb = torch.rand(3,4)

t_aa, t_bb

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [71]:
t_aa == t_bb

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# working with GPU

In [72]:
!nvidia-smi

Thu Jun  8 14:28:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [73]:
import torch
torch.cuda.is_available()

True

In [74]:
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [75]:
torch.cuda.device_count()

1

In [79]:
ts = torch.tensor([1,2,3])
ts, ts.device

(tensor([1, 2, 3]), device(type='cpu'))

In [80]:
ts_gpu = ts.to(device)
ts_gpu

tensor([1, 2, 3], device='cuda:0')

In [81]:
ts_gpu.numpy()

TypeError: ignored

In [83]:
ts_gpu_to_cpu = ts_gpu.cpu().numpy()
ts_gpu_to_cpu, ts_gpu_to_cpu.dtype

(array([1, 2, 3]), dtype('int64'))

In [84]:
ts_gpu

tensor([1, 2, 3], device='cuda:0')